name: Hourly Prognose Bot

on:
  schedule:
    - cron: "0 * * * *"  # jede volle Stunde
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run analysis and post
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
        run: python prognose_to_discord.py
